name: CI

on: [ pull_request ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.2' ]
    name: PHP ${{ matrix.php-versions }} Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          args: --prefer-dist
          php_version: ${{ matrix.php-versions }}

      - name: run phpspec
        run: vendor/bin/phpspec run
